# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text=b'Unic hash of the session', max_length=64, unique=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0421\u0435\u0441\u0441\u0438\u044f',
                'verbose_name_plural': '\u0421\u0435\u0441\u0441\u0438\u0438',
            },
        ),
    ]
