T_SNOWBOARDING = 1
T_SKIING = 2
TYPES_TRAINING = (
    (T_SNOWBOARDING,"T_SNOWBOARDING"),
    (T_SKIING, "T_SKIING"),
)

S_WAITS_FOR_COUCH = 1
S_APPROVED = 2
S_FINISHED = 3
STATUSES_TRAINING = (
    (S_WAITS_FOR_COUCH,"S_WAITS_FOR_COUCH"),
    (S_APPROVED,"S_APPROVED"),
    (S_FINISHED, "S_FINISHED"),
)