# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 15:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import re
import suser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('image', models.ImageField(blank=True, default='img/users/default.png', null=True, upload_to=suser.models.get_file_path)),
                ('phone', models.CharField(help_text='Phone number 9123456789', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'\\d{10,12}'), b'Enter a valid phone.', b'invalid')])),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('last_point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='last lang and lat', null=True, srid=4326)),
                ('position_measurement_time', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('google_cloud_id', models.CharField(blank=True, help_text='Id which user (dr and cus) takes from google cloud, for downstream messagging.', max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
    ]
