# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_couch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='short_info',
            field=models.TextField(blank=True, help_text='Short info about user', null=True),
        ),
    ]
